# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.project_ids_inner_ids import ProjectIdsInnerIds  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectIdsInnerIds(unittest.TestCase):
    """ProjectIdsInnerIds unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectIdsInnerIds(self):
        """Test ProjectIdsInnerIds"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.project_ids_inner_ids.ProjectIdsInnerIds()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
