# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projectids_api import ProjectidsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectidsApi(unittest.TestCase):
    """ProjectidsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectidsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_projects(self):
        """Test case for get_user_projects

        Get project ids of your created projects  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
