# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_rpp_data_collection_frequency import CreateRppDataCollectionFrequency  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateRppDataCollectionFrequency(unittest.TestCase):
    """CreateRppDataCollectionFrequency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateRppDataCollectionFrequency(self):
        """Test CreateRppDataCollectionFrequency"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_rpp_data_collection_frequency.CreateRppDataCollectionFrequency()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
