# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.update_api import UpdateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateApi(unittest.TestCase):
    """UpdateApi unit test stubs"""

    def setUp(self):
        self.api = UpdateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_rpp_project(self):
        """Test case for update_rpp_project

        Update Rank Tracker project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
