# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.create_api import CreateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateApi(unittest.TestCase):
    """CreateApi unit test stubs"""

    def setUp(self):
        self.api = CreateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_ad_words_project(self):
        """Test case for create_ad_words_project

        Create AdWords parsing project  # noqa: E501
        """
        pass

    def test_create_fpp_project(self):
        """Test case for create_fpp_project

        Create Fast Positions parsing project  # noqa: E501
        """
        pass

    def test_create_indexation_project(self):
        """Test case for create_indexation_project

        Create Indexation parsing project  # noqa: E501
        """
        pass

    def test_create_rpp_project(self):
        """Test case for create_rpp_project

        Create Rank Tracker project BETA  # noqa: E501
        """
        pass

    def test_create_suggest_project(self):
        """Test case for create_suggest_project

        Create Suggest parsing project  # noqa: E501
        """
        pass

    def test_create_top10_project(self):
        """Test case for create_top10_project

        Create Top 10 parsing project  # noqa: E501
        """
        pass

    def test_create_wordstat_project(self):
        """Test case for create_wordstat_project

        Create Wordstat parsing project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
