# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FppRegion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'id': 'int',
        'lang': 'str',
        'device': 'int'
    }

    attribute_map = {
        'type': 'type',
        'id': 'id',
        'lang': 'lang',
        'device': 'device'
    }

    def __init__(self, type=None, id=None, lang=None, device=None):  # noqa: E501
        """FppRegion - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._id = None
        self._lang = None
        self._device = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if id is not None:
            self.id = id
        if lang is not None:
            self.lang = lang
        if device is not None:
            self.device = device

    @property
    def type(self):
        """Gets the type of this FppRegion.  # noqa: E501


        :return: The type of this FppRegion.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FppRegion.


        :param type: The type of this FppRegion.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def id(self):
        """Gets the id of this FppRegion.  # noqa: E501


        :return: The id of this FppRegion.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FppRegion.


        :param id: The id of this FppRegion.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def lang(self):
        """Gets the lang of this FppRegion.  # noqa: E501


        :return: The lang of this FppRegion.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this FppRegion.


        :param lang: The lang of this FppRegion.  # noqa: E501
        :type: str
        """

        self._lang = lang

    @property
    def device(self):
        """Gets the device of this FppRegion.  # noqa: E501


        :return: The device of this FppRegion.  # noqa: E501
        :rtype: int
        """
        return self._device

    @device.setter
    def device(self, device):
        """Sets the device of this FppRegion.


        :param device: The device of this FppRegion.  # noqa: E501
        :type: int
        """

        self._device = device

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FppRegion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FppRegion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
