# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GdsVisibilityInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'group': 'str',
        'visibility_history': 'list[object]'
    }

    attribute_map = {
        'group': 'group',
        'visibility_history': 'visibility_history'
    }

    def __init__(self, group=None, visibility_history=None):  # noqa: E501
        """GdsVisibilityInner - a model defined in Swagger"""  # noqa: E501
        self._group = None
        self._visibility_history = None
        self.discriminator = None
        if group is not None:
            self.group = group
        if visibility_history is not None:
            self.visibility_history = visibility_history

    @property
    def group(self):
        """Gets the group of this GdsVisibilityInner.  # noqa: E501


        :return: The group of this GdsVisibilityInner.  # noqa: E501
        :rtype: str
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this GdsVisibilityInner.


        :param group: The group of this GdsVisibilityInner.  # noqa: E501
        :type: str
        """

        self._group = group

    @property
    def visibility_history(self):
        """Gets the visibility_history of this GdsVisibilityInner.  # noqa: E501


        :return: The visibility_history of this GdsVisibilityInner.  # noqa: E501
        :rtype: list[object]
        """
        return self._visibility_history

    @visibility_history.setter
    def visibility_history(self, visibility_history):
        """Sets the visibility_history of this GdsVisibilityInner.


        :param visibility_history: The visibility_history of this GdsVisibilityInner.  # noqa: E501
        :type: list[object]
        """

        self._visibility_history = visibility_history

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GdsVisibilityInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GdsVisibilityInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
