# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GdsPositionsInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'keyword': 'str',
        'group': 'str',
        'search_volume': 'str',
        'targeturl': 'str',
        'relevanturl': 'str',
        'traffic': 'int',
        'positions_history': 'list[object]'
    }

    attribute_map = {
        'keyword': 'keyword',
        'group': 'group',
        'search_volume': 'search_volume',
        'targeturl': 'targeturl',
        'relevanturl': 'relevanturl',
        'traffic': 'traffic',
        'positions_history': 'positions_history'
    }

    def __init__(self, keyword=None, group=None, search_volume=None, targeturl=None, relevanturl=None, traffic=None, positions_history=None):  # noqa: E501
        """GdsPositionsInner - a model defined in Swagger"""  # noqa: E501
        self._keyword = None
        self._group = None
        self._search_volume = None
        self._targeturl = None
        self._relevanturl = None
        self._traffic = None
        self._positions_history = None
        self.discriminator = None
        if keyword is not None:
            self.keyword = keyword
        if group is not None:
            self.group = group
        if search_volume is not None:
            self.search_volume = search_volume
        if targeturl is not None:
            self.targeturl = targeturl
        if relevanturl is not None:
            self.relevanturl = relevanturl
        if traffic is not None:
            self.traffic = traffic
        if positions_history is not None:
            self.positions_history = positions_history

    @property
    def keyword(self):
        """Gets the keyword of this GdsPositionsInner.  # noqa: E501


        :return: The keyword of this GdsPositionsInner.  # noqa: E501
        :rtype: str
        """
        return self._keyword

    @keyword.setter
    def keyword(self, keyword):
        """Sets the keyword of this GdsPositionsInner.


        :param keyword: The keyword of this GdsPositionsInner.  # noqa: E501
        :type: str
        """

        self._keyword = keyword

    @property
    def group(self):
        """Gets the group of this GdsPositionsInner.  # noqa: E501


        :return: The group of this GdsPositionsInner.  # noqa: E501
        :rtype: str
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this GdsPositionsInner.


        :param group: The group of this GdsPositionsInner.  # noqa: E501
        :type: str
        """

        self._group = group

    @property
    def search_volume(self):
        """Gets the search_volume of this GdsPositionsInner.  # noqa: E501


        :return: The search_volume of this GdsPositionsInner.  # noqa: E501
        :rtype: str
        """
        return self._search_volume

    @search_volume.setter
    def search_volume(self, search_volume):
        """Sets the search_volume of this GdsPositionsInner.


        :param search_volume: The search_volume of this GdsPositionsInner.  # noqa: E501
        :type: str
        """

        self._search_volume = search_volume

    @property
    def targeturl(self):
        """Gets the targeturl of this GdsPositionsInner.  # noqa: E501


        :return: The targeturl of this GdsPositionsInner.  # noqa: E501
        :rtype: str
        """
        return self._targeturl

    @targeturl.setter
    def targeturl(self, targeturl):
        """Sets the targeturl of this GdsPositionsInner.


        :param targeturl: The targeturl of this GdsPositionsInner.  # noqa: E501
        :type: str
        """

        self._targeturl = targeturl

    @property
    def relevanturl(self):
        """Gets the relevanturl of this GdsPositionsInner.  # noqa: E501


        :return: The relevanturl of this GdsPositionsInner.  # noqa: E501
        :rtype: str
        """
        return self._relevanturl

    @relevanturl.setter
    def relevanturl(self, relevanturl):
        """Sets the relevanturl of this GdsPositionsInner.


        :param relevanturl: The relevanturl of this GdsPositionsInner.  # noqa: E501
        :type: str
        """

        self._relevanturl = relevanturl

    @property
    def traffic(self):
        """Gets the traffic of this GdsPositionsInner.  # noqa: E501


        :return: The traffic of this GdsPositionsInner.  # noqa: E501
        :rtype: int
        """
        return self._traffic

    @traffic.setter
    def traffic(self, traffic):
        """Sets the traffic of this GdsPositionsInner.


        :param traffic: The traffic of this GdsPositionsInner.  # noqa: E501
        :type: int
        """

        self._traffic = traffic

    @property
    def positions_history(self):
        """Gets the positions_history of this GdsPositionsInner.  # noqa: E501


        :return: The positions_history of this GdsPositionsInner.  # noqa: E501
        :rtype: list[object]
        """
        return self._positions_history

    @positions_history.setter
    def positions_history(self, positions_history):
        """Sets the positions_history of this GdsPositionsInner.


        :param positions_history: The positions_history of this GdsPositionsInner.  # noqa: E501
        :type: list[object]
        """

        self._positions_history = positions_history

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GdsPositionsInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GdsPositionsInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
