# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'status': 'str',
        'resulturl': 'str'
    }

    attribute_map = {
        'id': 'id',
        'status': 'status',
        'resulturl': 'resulturl'
    }

    def __init__(self, id=None, status=None, resulturl=None):  # noqa: E501
        """ProjectStatus - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._status = None
        self._resulturl = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if status is not None:
            self.status = status
        if resulturl is not None:
            self.resulturl = resulturl

    @property
    def id(self):
        """Gets the id of this ProjectStatus.  # noqa: E501


        :return: The id of this ProjectStatus.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProjectStatus.


        :param id: The id of this ProjectStatus.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def status(self):
        """Gets the status of this ProjectStatus.  # noqa: E501


        :return: The status of this ProjectStatus.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ProjectStatus.


        :param status: The status of this ProjectStatus.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def resulturl(self):
        """Gets the resulturl of this ProjectStatus.  # noqa: E501


        :return: The resulturl of this ProjectStatus.  # noqa: E501
        :rtype: str
        """
        return self._resulturl

    @resulturl.setter
    def resulturl(self, resulturl):
        """Sets the resulturl of this ProjectStatus.


        :param resulturl: The resulturl of this ProjectStatus.  # noqa: E501
        :type: str
        """

        self._resulturl = resulturl

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
