# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SuggestParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'apikey': 'str',
        'name': 'str',
        'yandex_region_id': 'int',
        'google_region': 'SuggestParametersGoogleRegion',
        'youtube_region': 'SuggestParametersGoogleRegion',
        'depth': 'int',
        'keywords': 'list[str]',
        'stopwords': 'list[str]'
    }

    attribute_map = {
        'apikey': 'apikey',
        'name': 'name',
        'yandex_region_id': 'yandexRegionId',
        'google_region': 'googleRegion',
        'youtube_region': 'youtubeRegion',
        'depth': 'depth',
        'keywords': 'keywords',
        'stopwords': 'stopwords'
    }

    def __init__(self, apikey=None, name=None, yandex_region_id=None, google_region=None, youtube_region=None, depth=None, keywords=None, stopwords=None):  # noqa: E501
        """SuggestParameters - a model defined in Swagger"""  # noqa: E501
        self._apikey = None
        self._name = None
        self._yandex_region_id = None
        self._google_region = None
        self._youtube_region = None
        self._depth = None
        self._keywords = None
        self._stopwords = None
        self.discriminator = None
        if apikey is not None:
            self.apikey = apikey
        if name is not None:
            self.name = name
        if yandex_region_id is not None:
            self.yandex_region_id = yandex_region_id
        if google_region is not None:
            self.google_region = google_region
        if youtube_region is not None:
            self.youtube_region = youtube_region
        if depth is not None:
            self.depth = depth
        if keywords is not None:
            self.keywords = keywords
        if stopwords is not None:
            self.stopwords = stopwords

    @property
    def apikey(self):
        """Gets the apikey of this SuggestParameters.  # noqa: E501


        :return: The apikey of this SuggestParameters.  # noqa: E501
        :rtype: str
        """
        return self._apikey

    @apikey.setter
    def apikey(self, apikey):
        """Sets the apikey of this SuggestParameters.


        :param apikey: The apikey of this SuggestParameters.  # noqa: E501
        :type: str
        """

        self._apikey = apikey

    @property
    def name(self):
        """Gets the name of this SuggestParameters.  # noqa: E501


        :return: The name of this SuggestParameters.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SuggestParameters.


        :param name: The name of this SuggestParameters.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def yandex_region_id(self):
        """Gets the yandex_region_id of this SuggestParameters.  # noqa: E501


        :return: The yandex_region_id of this SuggestParameters.  # noqa: E501
        :rtype: int
        """
        return self._yandex_region_id

    @yandex_region_id.setter
    def yandex_region_id(self, yandex_region_id):
        """Sets the yandex_region_id of this SuggestParameters.


        :param yandex_region_id: The yandex_region_id of this SuggestParameters.  # noqa: E501
        :type: int
        """

        self._yandex_region_id = yandex_region_id

    @property
    def google_region(self):
        """Gets the google_region of this SuggestParameters.  # noqa: E501


        :return: The google_region of this SuggestParameters.  # noqa: E501
        :rtype: SuggestParametersGoogleRegion
        """
        return self._google_region

    @google_region.setter
    def google_region(self, google_region):
        """Sets the google_region of this SuggestParameters.


        :param google_region: The google_region of this SuggestParameters.  # noqa: E501
        :type: SuggestParametersGoogleRegion
        """

        self._google_region = google_region

    @property
    def youtube_region(self):
        """Gets the youtube_region of this SuggestParameters.  # noqa: E501


        :return: The youtube_region of this SuggestParameters.  # noqa: E501
        :rtype: SuggestParametersGoogleRegion
        """
        return self._youtube_region

    @youtube_region.setter
    def youtube_region(self, youtube_region):
        """Sets the youtube_region of this SuggestParameters.


        :param youtube_region: The youtube_region of this SuggestParameters.  # noqa: E501
        :type: SuggestParametersGoogleRegion
        """

        self._youtube_region = youtube_region

    @property
    def depth(self):
        """Gets the depth of this SuggestParameters.  # noqa: E501


        :return: The depth of this SuggestParameters.  # noqa: E501
        :rtype: int
        """
        return self._depth

    @depth.setter
    def depth(self, depth):
        """Sets the depth of this SuggestParameters.


        :param depth: The depth of this SuggestParameters.  # noqa: E501
        :type: int
        """

        self._depth = depth

    @property
    def keywords(self):
        """Gets the keywords of this SuggestParameters.  # noqa: E501


        :return: The keywords of this SuggestParameters.  # noqa: E501
        :rtype: list[str]
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords):
        """Sets the keywords of this SuggestParameters.


        :param keywords: The keywords of this SuggestParameters.  # noqa: E501
        :type: list[str]
        """

        self._keywords = keywords

    @property
    def stopwords(self):
        """Gets the stopwords of this SuggestParameters.  # noqa: E501


        :return: The stopwords of this SuggestParameters.  # noqa: E501
        :rtype: list[str]
        """
        return self._stopwords

    @stopwords.setter
    def stopwords(self, stopwords):
        """Sets the stopwords of this SuggestParameters.


        :param stopwords: The stopwords of this SuggestParameters.  # noqa: E501
        :type: list[str]
        """

        self._stopwords = stopwords

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SuggestParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SuggestParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
