# coding: utf-8

"""
    Rush Analytics API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2
    Contact: support@rushanalytics.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class GdsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def gds_competitors_visibility(self, projectid, apikey, **kwargs):  # noqa: E501
        """Get competitors visibility data of your rank tracker project for Google Data Studio  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gds_competitors_visibility(projectid, apikey, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int projectid: Project ID (required)
        :param str apikey: Your api key (required)
        :return: GdsCompetitorsVisibility
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gds_competitors_visibility_with_http_info(projectid, apikey, **kwargs)  # noqa: E501
        else:
            (data) = self.gds_competitors_visibility_with_http_info(projectid, apikey, **kwargs)  # noqa: E501
            return data

    def gds_competitors_visibility_with_http_info(self, projectid, apikey, **kwargs):  # noqa: E501
        """Get competitors visibility data of your rank tracker project for Google Data Studio  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gds_competitors_visibility_with_http_info(projectid, apikey, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int projectid: Project ID (required)
        :param str apikey: Your api key (required)
        :return: GdsCompetitorsVisibility
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['projectid', 'apikey']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gds_competitors_visibility" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'projectid' is set
        if ('projectid' not in params or
                params['projectid'] is None):
            raise ValueError("Missing the required parameter `projectid` when calling `gds_competitors_visibility`")  # noqa: E501
        # verify the required parameter 'apikey' is set
        if ('apikey' not in params or
                params['apikey'] is None):
            raise ValueError("Missing the required parameter `apikey` when calling `gds_competitors_visibility`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'projectid' in params:
            path_params['projectid'] = params['projectid']  # noqa: E501

        query_params = []
        if 'apikey' in params:
            query_params.append(('apikey', params['apikey']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gds/competitors_visibility/{projectid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GdsCompetitorsVisibility',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gds_positions(self, projectid, apikey, **kwargs):  # noqa: E501
        """Get positions history of your rank tracker project for Google Data Studio  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gds_positions(projectid, apikey, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int projectid: Project ID (required)
        :param str apikey: Your api key (required)
        :return: GdsPositions
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gds_positions_with_http_info(projectid, apikey, **kwargs)  # noqa: E501
        else:
            (data) = self.gds_positions_with_http_info(projectid, apikey, **kwargs)  # noqa: E501
            return data

    def gds_positions_with_http_info(self, projectid, apikey, **kwargs):  # noqa: E501
        """Get positions history of your rank tracker project for Google Data Studio  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gds_positions_with_http_info(projectid, apikey, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int projectid: Project ID (required)
        :param str apikey: Your api key (required)
        :return: GdsPositions
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['projectid', 'apikey']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gds_positions" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'projectid' is set
        if ('projectid' not in params or
                params['projectid'] is None):
            raise ValueError("Missing the required parameter `projectid` when calling `gds_positions`")  # noqa: E501
        # verify the required parameter 'apikey' is set
        if ('apikey' not in params or
                params['apikey'] is None):
            raise ValueError("Missing the required parameter `apikey` when calling `gds_positions`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'projectid' in params:
            path_params['projectid'] = params['projectid']  # noqa: E501

        query_params = []
        if 'apikey' in params:
            query_params.append(('apikey', params['apikey']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gds/positions/{projectid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GdsPositions',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gds_schema(self, projectid, apikey, **kwargs):  # noqa: E501
        """Get schema of your rank tracker project for Google Data Studio  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gds_schema(projectid, apikey, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int projectid: Project ID (required)
        :param str apikey: Your api key (required)
        :return: GdsSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gds_schema_with_http_info(projectid, apikey, **kwargs)  # noqa: E501
        else:
            (data) = self.gds_schema_with_http_info(projectid, apikey, **kwargs)  # noqa: E501
            return data

    def gds_schema_with_http_info(self, projectid, apikey, **kwargs):  # noqa: E501
        """Get schema of your rank tracker project for Google Data Studio  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gds_schema_with_http_info(projectid, apikey, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int projectid: Project ID (required)
        :param str apikey: Your api key (required)
        :return: GdsSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['projectid', 'apikey']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gds_schema" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'projectid' is set
        if ('projectid' not in params or
                params['projectid'] is None):
            raise ValueError("Missing the required parameter `projectid` when calling `gds_schema`")  # noqa: E501
        # verify the required parameter 'apikey' is set
        if ('apikey' not in params or
                params['apikey'] is None):
            raise ValueError("Missing the required parameter `apikey` when calling `gds_schema`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'projectid' in params:
            path_params['projectid'] = params['projectid']  # noqa: E501

        query_params = []
        if 'apikey' in params:
            query_params.append(('apikey', params['apikey']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gds/schema/{projectid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GdsSchema',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gds_tops(self, projectid, apikey, **kwargs):  # noqa: E501
        """Get tops (100,30,10,5,3) data of your rank tracker project for Google Data Studio  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gds_tops(projectid, apikey, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int projectid: Project ID (required)
        :param str apikey: Your api key (required)
        :return: GdsTops
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gds_tops_with_http_info(projectid, apikey, **kwargs)  # noqa: E501
        else:
            (data) = self.gds_tops_with_http_info(projectid, apikey, **kwargs)  # noqa: E501
            return data

    def gds_tops_with_http_info(self, projectid, apikey, **kwargs):  # noqa: E501
        """Get tops (100,30,10,5,3) data of your rank tracker project for Google Data Studio  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gds_tops_with_http_info(projectid, apikey, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int projectid: Project ID (required)
        :param str apikey: Your api key (required)
        :return: GdsTops
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['projectid', 'apikey']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gds_tops" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'projectid' is set
        if ('projectid' not in params or
                params['projectid'] is None):
            raise ValueError("Missing the required parameter `projectid` when calling `gds_tops`")  # noqa: E501
        # verify the required parameter 'apikey' is set
        if ('apikey' not in params or
                params['apikey'] is None):
            raise ValueError("Missing the required parameter `apikey` when calling `gds_tops`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'projectid' in params:
            path_params['projectid'] = params['projectid']  # noqa: E501

        query_params = []
        if 'apikey' in params:
            query_params.append(('apikey', params['apikey']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gds/tops/{projectid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GdsTops',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def gds_visibility(self, projectid, apikey, **kwargs):  # noqa: E501
        """Get competitors visibility data of your rank tracker project for Google Data Studio  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gds_visibility(projectid, apikey, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int projectid: Project ID (required)
        :param str apikey: Your api key (required)
        :return: GdsVisibility
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.gds_visibility_with_http_info(projectid, apikey, **kwargs)  # noqa: E501
        else:
            (data) = self.gds_visibility_with_http_info(projectid, apikey, **kwargs)  # noqa: E501
            return data

    def gds_visibility_with_http_info(self, projectid, apikey, **kwargs):  # noqa: E501
        """Get competitors visibility data of your rank tracker project for Google Data Studio  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.gds_visibility_with_http_info(projectid, apikey, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int projectid: Project ID (required)
        :param str apikey: Your api key (required)
        :return: GdsVisibility
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['projectid', 'apikey']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method gds_visibility" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'projectid' is set
        if ('projectid' not in params or
                params['projectid'] is None):
            raise ValueError("Missing the required parameter `projectid` when calling `gds_visibility`")  # noqa: E501
        # verify the required parameter 'apikey' is set
        if ('apikey' not in params or
                params['apikey'] is None):
            raise ValueError("Missing the required parameter `apikey` when calling `gds_visibility`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'projectid' in params:
            path_params['projectid'] = params['projectid']  # noqa: E501

        query_params = []
        if 'apikey' in params:
            query_params.append(('apikey', params['apikey']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/gds/visibility/{projectid}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GdsVisibility',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
